import { Inter } from "next/font/google";
import "../../app/globals.css";
import Head from "next/head";
import Dropdown from "react-bootstrap/Dropdown";
import NotificationsActiveIcon from "@mui/icons-material/NotificationsActive";
import DashboardIcon from "@mui/icons-material/Dashboard";
import Image from "next/image";
import ArrowForwardIosIcon from "@mui/icons-material/ArrowForwardIos";
import Link from "next/link";
import PersonIcon from "@mui/icons-material/Person";
import LockIcon from "@mui/icons-material/Lock";
import EmailIcon from "@mui/icons-material/Email";
import KeyIcon from "@mui/icons-material/Key";
import { useState, useEffect } from "react";
import { NavLink } from "react-bootstrap";
import { useParams, useRouter } from "next/navigation";
import KeyboardArrowRightIcon from "@mui/icons-material/KeyboardArrowRight";
import KeyboardArrowDownIcon from "@mui/icons-material/KeyboardArrowDown";
import axios from "axios";
import BaseAPI from "../BaseAPI/BaseAPI";
import "@fortawesome/fontawesome-free/css/all.css";

import Swal from "sweetalert2";
import Cookies from "js-cookie";
// import '../newcommon.css'
import "../common.css";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LS::RMS",
  description: "Generated by create next app",
  icons: {
    icon: ["/Images/favicon.ico"],

    sizes: "192x192",
    type: "image/png",
  },
};

export default function RootLayout({ children }) {
  const router = useRouter();

  const fname = Cookies.get("fname");
  const token = Cookies.get("token");
  const adminId = Cookies.get("adminId");
  const employerId = Cookies.get("employerId");
  const tokenEmployer = Cookies.get("tokenEmployer");
  const fnameEmployer = Cookies.get("fnameEmployer");
  const userType = Cookies.get("userType");


  const [logoData, setLogoData] = useState([]);

  const urlData = usePathname();
  const images = Cookies.get("admin_profile_picture");
  const toggleSidebar = () => {
    setSidebarDisplay(!sidebarDisplay);
  };

  // console.log(images);

  // console.log('Current Path:', urlData)
  // const slug = params.slug;

  const [sidebarDisplay, setSidebarDisplay] = useState(false);
  const [showConfigurationDropdown, setShowConfigurationDropdown] =
    useState(false);
  const handleSidebarDisplay = () => {
    setSidebarDisplay(!sidebarDisplay);
  };

  const [sidebarOpen, setSidebarOpen] = useState(false);

  const { slug } = useParams();
  useEffect(() => {
    // Check if the current URL matches any of the dropdown menu items
    if (
      urlData === "/admin/changeusername" ||
      urlData === "/admin/changepassword" ||
      urlData === "/admin/changeemail" ||
      urlData === "/admin/changeprofilepicture" ||
      urlData === "/admin/generalsetting" ||
      urlData === "/admin/uploadlogo" ||
      urlData === "/admin/processmanagement" ||
      urlData === "/admin/processmanagement/add" ||
      urlData === `/admin/processmanagement/edit/${slug}` ||
      urlData === "/admin/statusmanagement" ||
      urlData === "/admin/statusmanagement/addstatus" ||
      urlData === `/admin/statusmanagement/edit/${slug}` ||
      urlData === "/admin/assignusertointerview" ||
      urlData === `/admin/assignusertointerview/edit/${slug}` ||
      urlData === "/admin/assignnewprocess"
    ) {
      setShowConfigurationDropdown(true);
    } else {
      setShowConfigurationDropdown(false);
    }
  }, [urlData]);

  const handleLogOut = async () => {
    try {
      const confirmationResult = await Swal.fire({
        title: "Logout?",
        text: "Do you want to logout?",
        icon: "question",
        showCancelButton: true,
        confirmButtonText: "Yes",
        cancelButtonText: "No",
      });
      if (confirmationResult.isConfirmed) {
        const response = await axios.post(BaseAPI + "/admin/logout", null, {
          headers: {
            "Content-Type": "application/json",
            // key: ApiKey,
            Authorization: "Bearer" + " " + token,
          },
        });
        Cookies.remove("token");
        Cookies.remove("fname");
        // sessionStorage.clear();
        router.push("/admin/login");
        window.location.reload();
        const Toast = Swal.mixin({
          toast: true,
          position: "top-end",
          showConfirmButton: false,
          timer: 3000,
          timerProgressBar: true,
          didOpen: (toast) => {
            toast.addEventListener("mouseenter", Swal.stopTimer);
            toast.addEventListener("mouseleave", Swal.resumeTimer);
          },
        });

        Toast.fire({
          icon: "success",
          title: "Logout successful",
        });
      }
    } catch (error) {
      Swal.fire({
        title: "Could not log you out",
        icon: "error",
        confirmButtonText: "Close",
      });
      console.log("Cannot logout!");
    }
  };

  const getData = async () => {
    try {
      const response = await axios.post(
        BaseAPI + "/admin/changeprofilepicture",
        null, // Pass null as the request body if not required
        {
          headers: {
            "Content-Type": "application/json",
            // key: ApiKey,
            Authorization: "Bearer" + " " + token || tokenEmployer,
            // adminid: adminID,
          },
        }
      );

      setLogoData(response.data.response.logo_path);

      Cookies.set("admin_profile_picture", response.data.response.logo_path);
    } catch (error) {
      // setLoading(false);
      console.log("Cannot get profile photo data");
    }
  };

  useEffect(() => {
    window.innerWidth < 768
      ? setSidebarDisplay(true)
      : setSidebarDisplay(false);
  }, []);

  const [isMobile, setIsMobile] = useState(false);

  const checkIsMobile = () => {
    setIsMobile(window.innerWidth <= 768); // Adjust the breakpoint as needed
  };

  useEffect(() => {
    checkIsMobile();
    window.addEventListener("resize", checkIsMobile);
    return () => {
      window.removeEventListener("resize", checkIsMobile);
    };
  }, []);

  // useEffect(() => {
  //   getData();
  //   // window.scrollTo(0, 0);
  //   // eslint-disable-next-line
  // }, [getData]);

  return (
    <html lang="en">
      <Head></Head>

      <body className={inter.className}>
        <div
          // className="adminPageLeft"
          // style={{ display: sidebarDisplay ? "none" : "block" }}
          className={`adminPageLeft ${isMobile ? "mobile" : ""}`}
          style={{ display: sidebarDisplay ? "none" : "block" }}
        >
          <aside>
            <div className="sidebar   ">
              {isMobile && (
                <button
                  className="closeBtn text-dark w-100 "
                  onClick={toggleSidebar}
                >
                  <i className="fas fa-times"></i>
                </button>
              )}
              <div className="profile-name--bx">
                <div className="logo">
                  {logoData ? (
                    <img
                      src={images}
                      alt="Company Logo"
                      width={180}
                      height={180}
                      style={{ borderRadius: "50%" }}
                    />
                  ) : (
                    <img
                      src="/Images/adminSide/HimanshuMane.jpg"
                      alt="Company Logo"
                      width={180}
                      height={180}
                    />
                  )}
                </div>
                {/* {fnameEmployer && <h3>{fnameEmployer ? fnameEmployer : "User"}</h3>} */}
                {fname && <h3>{fname ? fname : "User"}</h3>}
                <h4 className="mt-2">
                  {adminId === "1" && "Admin"}
                  {/* {employerId && "Employer"}  */}
                </h4>
              </div>

              <ul className="sidebar-menu">
                <Link href="/admin/dashboard" className="sub-category">
                  <li
                    className={`sub-menu ${
                      urlData === "/admin/dashboard" ? "sidebarActive" : ""
                    }`}
                  >
                    <i className="fa-solid fa-gauge"></i>
                    <span>Dashboard</span>
                  </li>
                </Link>
                <li
                  className={`sub-menu ${
                    urlData === "/admin/changeusername" ||
                    urlData === "/admin/changepassword" ||
                    urlData === "/admin/changeemail" ||
                    urlData === "/admin/changeprofilepicture" ||
                    urlData === "/admin/generalsetting" ||
                    urlData === "/admin/uploadLogo" ||
                    urlData === "/admin/interviewprocess" ||
                    urlData === "/admin/addinterviewprocess" ||
                    urlData === "/admin/updateinterviewprocess/1" ||
                    urlData === "/admin/statusmanagement" ||
                    urlData === "/admin/addinterviewstatus" ||
                    urlData === "/admin/updateinterviewstatus" ||
                    urlData === "/admin/assignusertointerview"
                      ? "sidebarActive"
                      : ""
                  }`}
                  onClick={() =>
                    setShowConfigurationDropdown(!showConfigurationDropdown)
                  }
                >
                  <Link
                    href=""
                    className={`sub-category 
                    `}
                  >
                    <div className="eachMenuItem">
                      <div className="menuLeftSection">
                        <i className="fa fa-gears"></i>
                        <span>Configuration </span>
                      </div>

                      {showConfigurationDropdown ? (
                        <div id="icon2">
                          <KeyboardArrowDownIcon />
                        </div>
                      ) : (
                        <div id="icon2">
                          <KeyboardArrowRightIcon />
                        </div>
                      )}
                    </div>
                  </Link>
                </li>
                <div
                  className={`dropdown ${
                    showConfigurationDropdown ? "open" : ""
                  }`}
                >
                  <div className="dropdown-item">
                    <ul className="SidebarListInternal">
                      <NavLink href="/admin/changeusername">
                        <li
                          className={`row ${
                            urlData === "/admin/changeusername" ? "active" : ""
                          }`}
                        >
                          <p
                            id="title"
                            className={
                              urlData === "/admin/changeusername"
                                ? "sidebarDropdownActive"
                                : ""
                            }
                          >
                            Change Username
                          </p>
                        </li>
                      </NavLink>
                      <NavLink href="/admin/changepassword">
                        <li
                          className={`row ${
                            urlData === "/admin/changepassword" ? "active" : ""
                          }`}
                        >
                          <p
                            id="title"
                            className={
                              urlData === "/admin/changepassword"
                                ? "sidebarDropdownActive"
                                : ""
                            }
                          >
                            Change Password
                          </p>
                        </li>
                      </NavLink>
                      <NavLink href="/admin/changeemail">
                        <li
                          className={`row ${
                            urlData === "/admin/changeemail" ? "active" : ""
                          }`}
                        >
                          <p
                            id="title"
                            className={
                              urlData === "/admin/changeemail"
                                ? "sidebarDropdownActive"
                                : ""
                            }
                          >
                            Change Email
                          </p>
                        </li>
                      </NavLink>
                      <NavLink href="/admin/changeprofilepicture">
                        <li
                          className={`row ${
                            urlData === "/admin/changeprofilepicture"
                              ? "active"
                              : ""
                          }`}
                        >
                          <p
                            id="title"
                            className={
                              urlData === "/admin/changeprofilepicture"
                                ? "sidebarDropdownActive"
                                : ""
                            }
                          >
                            Change Profile Picture
                          </p>
                        </li>
                      </NavLink>
                      <NavLink href="/admin/generalsetting">
                        <li
                          className={`row ${
                            urlData === "/admin/generalsetting" ? "active" : ""
                          }`}
                        >
                          <p
                            id="title"
                            className={
                              urlData === "/admin/generalsetting"
                                ? "sidebarDropdownActive"
                                : ""
                            }
                          >
                            General Setting
                          </p>
                        </li>
                      </NavLink>
                      {adminId === "1" && (
                        <>
                          <NavLink href="/admin/uploadlogo">
                            <li
                              className={`row ${
                                urlData === "/admin/uploadlogo" ? "active" : ""
                              }`}
                            >
                              <p
                                id="title"
                                className={
                                  urlData === "/admin/uploadlogo"
                                    ? "sidebarDropdownActive"
                                    : ""
                                }
                              >
                                Change Logo
                              </p>
                            </li>
                          </NavLink>

                          <NavLink href="/admin/processmanagement">
                            <li
                              className={`row ${
                                urlData === "/admin/interviewprocess" ||
                                urlData === "/admin/processmanagement/add" ||
                                urlData ===
                                  `/admin/processmanagement/edit/${slug}`
                                  ? "active"
                                  : ""
                              }`}
                            >
                              <p
                                id="title"
                                className={
                                  urlData === "/admin/processmanagement" ||
                                  urlData === "/admin/processmanagement/add" ||
                                  urlData ===
                                    `/admin/processmanagement/edit/${slug}`
                                    ? "sidebarDropdownActive"
                                    : ""
                                }
                              >
                                Interview Process
                              </p>
                            </li>
                          </NavLink>

                          <NavLink href="/admin/statusmanagement">
                            <li
                              className={`row ${
                                urlData === "/admin/statusmanagement" ||
                                urlData ===
                                  "/admin/statusmanagement/addstatus" ||
                                urlData ===
                                  `/admin/statusmanagement/edit/${slug}`
                                  ? "active"
                                  : ""
                              }`}
                            >
                              <p
                                id="title"
                                className={
                                  urlData === "/admin/statusmanagement" ||
                                  urlData ===
                                    "/admin/statusmanagement/addstatus" ||
                                  urlData ===
                                    `/admin/statusmanagement/edit/${slug}`
                                    ? "sidebarDropdownActive"
                                    : ""
                                }
                              >
                                Status Management
                              </p>
                            </li>
                          </NavLink>
                          <NavLink href="/admin/assignusertointerview">
                            <li
                              className={`row ${
                                urlData === "/admin/assignusertointerview" ||
                                urlData === "/admin/assignnewprocess" ||
                                urlData ===
                                  `/admin/assignusertointerview/edit/${slug}`
                                  ? "active"
                                  : ""
                              }`}
                            >
                              <p
                                id="title"
                                className={
                                  urlData === "/admin/assignusertointerview" ||
                                  urlData === "/admin/assignnewprocess" ||
                                  urlData ===
                                    `/admin/assignusertointerview/edit/${slug}`
                                    ? "sidebarDropdownActive"
                                    : ""
                                }
                              >
                                Assign Users to the interview
                              </p>
                            </li>
                          </NavLink>
                        </>
                      )}
                    </ul>
                  </div>
                </div>

                {adminId === "1" && (
                  <>
                    <Link href="/admin/managesubadmin" className="sub-category">
                      <li
                        className={`sub-menu ${
                          urlData === "/admin/managesubadmin" ||
                          urlData === "/admin/managesubadmin/add" ||
                          urlData === "/admin/managesubadmin/edit"
                            ? "sidebarActive"
                            : ""
                        }`}
                      >
                        <i className="fa fa-users"></i>
                        <span>Manage Sub Admin</span>
                      </li>
                    </Link>

                    <Link href="/admin/categories" className="sub-category">
                      <li
                        className={`sub-menu ${
                          urlData === "/admin/categories" ||
                          urlData === "/admin/categories/add" ||
                          urlData === "/admin/categories/edit"
                            ? "sidebarActive"
                            : ""
                        }`}
                      >
                        <i className="fa fa-sitemap"></i>
                        <span>Category List</span>
                      </li>
                    </Link>
                    <Link href="/admin/jobs/postjobs" className="sub-category">
                      <li
                        className={`sub-menu ${
                          urlData === "/admin/jobs/postjobs"
                            ? "sidebarActive"
                            : ""
                        }`}
                      >
                        <i className="fa fa-suitcase"></i>
                        <span>Post Job</span>
                      </li>
                    </Link>
                    <Link href="/admin/jobs" className="sub-category">
                      <li
                        className={`sub-menu ${
                          urlData === "/admin/jobs" ? "sidebarActive" : ""
                        }`}
                      >
                        <i className="fa fa-list-alt"></i>
                        <span>Job</span>
                      </li>
                    </Link>

                    <Link
                      href="/admin/interview/candidate"
                      className="sub-category"
                    >
                      <li
                        className={`sub-menu ${
                          urlData === "/admin/interview/candidate"
                            ? "sidebarActive"
                            : ""
                        }`}
                      >
                        <i className="fa fa-user"></i>
                        <span>Applicant List</span>
                      </li>
                    </Link>
                  </>
                )}

                <Link
                  href="/admin/interview/newassigned"
                  className="sub-category"
                >
                  <li
                    className={`sub-menu ${
                      urlData === "/admin/interview/newassigned"
                        ? "sidebarActive"
                        : ""
                    }`}
                  >
                    <i class="fa-solid fa-clipboard-question"></i>
                    <span>Interviews Assigned</span>
                  </li>
                </Link>

                {adminId === "1" && (
                  <>
                    <Link href="/admin/skills" className="sub-category">
                      <li
                        className={`sub-menu ${
                          urlData === "/admin/skills" ||
                          urlData === "/admin/addskills" ||
                          urlData === "/admin/edit"
                            ? "sidebarActive"
                            : ""
                        }`}
                      >
                        <i class="fa-solid fa-atom"></i>
                        <span>Skill List</span>
                      </li>
                    </Link>

                    <Link
                      href="/admin/qualificationlist"
                      className="sub-category"
                    >
                      <li
                        className={`sub-menu ${
                          urlData === "/admin/qualificationlist" ||
                          urlData === "/admin/addqualification" ||
                          urlData === "/admin/updatequalification"
                            ? "sidebarActive"
                            : ""
                        }`}
                      >
                        <i class="fa-solid fa-graduation-cap"></i>
                        <span>Qualification List</span>
                      </li>
                    </Link>

                    <Link href="/admin/industry" className="sub-category">
                      <li
                        className={`sub-menu ${
                          urlData === "/admin/industry" ||
                          urlData === "/admin/industry/add" ||
                          urlData === "/admin/updateindustry"
                            ? "sidebarActive"
                            : ""
                        }`}
                      >
                        <i class="fa-solid fa-industry"></i>
                        <span>Industry List</span>
                      </li>
                    </Link>

                    <Link href="/admin/designation" className="sub-category">
                      <li
                        className={`sub-menu ${
                          urlData === "/admin/designation" ||
                          urlData === "/admin/designation/add" ||
                          urlData === "/admin/edit"
                            ? "sidebarActive"
                            : ""
                        }`}
                      >
                        <i class="fa-solid fa-briefcase"></i>
                        <span>Designation</span>
                      </li>
                    </Link>

                    <Link href="/admin/manageemployer" className="sub-category">
                      <li
                        className={`sub-menu ${
                          urlData === "/admin/manageemployer" ||
                          urlData === "/admin/manageemployer/add" ||
                          urlData === "/admin/manageemployer/edit/"
                            ? "sidebarActive"
                            : ""
                        }`}
                      >
                        <i class="fas fa-users"></i>
                        <span>Manage Employer</span>
                      </li>
                    </Link>
                    <Link href="/admin/managestaff" className="sub-category">
                      <li
                        className={`sub-menu ${
                          urlData === "/admin/managestaff" ||
                          urlData === "/admin/managestaff/add" ||
                          urlData === "/admin/managestaff/edit/" 
                            ? "sidebarActive"
                            : ""
                        }`}
                      >
                        <i class="fas fa-users"></i>

                        <span>Manage staff</span>
                      </li>
                    </Link>
                  </>
                )}

                <Link href="" className={`sub-category`} onClick={handleLogOut}>
                  <li className="sub-menu">
                    <i class="fas fa-sign-out-alt"></i>
                    <span>Logout</span>
                  </li>
                </Link>
              </ul>
            </div>
          </aside>
        </div>

        <div
          className="adminPageRight backgroundColor"
          style={{ paddingLeft: sidebarDisplay ? "0" : "266px" }}
        >
          <nav>
            <div className="adminNavbar">
              <div className="leftSide" onClick={handleSidebarDisplay}>
                <DashboardIcon />
                <span className="navLogo">
                  <Image
                    src="/Images/adminSide/rms-logo.png"
                    alt="logo"
                    width={50}
                    height={50}
                  />
                </span>
              </div>
              <div className="rightSide gap-1">
                <div className="icon">
                  <NotificationsActiveIcon />
                </div>
                <div className="userIcon flex items-center gap-2">
                  {logoData ? (
                    <img
                      src={logoData}
                      alt="Company Logo"
                      width={180}
                      height={180}
                      style={{ borderRadius: "50%" }}
                    />
                  ) : (
                    <img
                      src="/Images/adminSide/HimanshuMane.jpg"
                      alt="Company Logo"
                      width={180}
                      height={180}
                    />
                  )}
                  {/* <Image
                    src='/Images/adminSide/HimanshuMane.jpg'
                    alt='user-image'
                    width={50}
                    height={50}
                  /> */}
                  <Dropdown>
                    <Dropdown.Toggle className="bg-white text-black">
                      <ArrowForwardIosIcon fontSize="smaller" />
                    </Dropdown.Toggle>
                    <Dropdown.Menu>
                      <Dropdown.Item>
                        <div className="">
                          <ul
                            className=" custom-dropdown-menu"
                            aria-labelledby="dropdownMenuButton1"
                          >
                            <li className=" text-black">
                              <Link href="/admin/changeusername">
                                <PersonIcon />
                                <span>Change Username</span>
                              </Link>
                            </li>
                            <li className="">
                              <Link href="/admin/changepassword">
                                <LockIcon />
                                <span>Change Password</span>
                              </Link>
                            </li>
                            <li className="">
                              <Link href="/admin/changeemail">
                                <EmailIcon />
                                <span>Change Email</span>
                              </Link>
                            </li>
                            <li className="logOutButton" onClick={handleLogOut}>
                              <KeyIcon />
                              Logout
                            </li>
                          </ul>
                        </div>
                      </Dropdown.Item>
                    </Dropdown.Menu>
                  </Dropdown>
                </div>
              </div>
            </div>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
