import { Inter } from "next/font/google";
import "../../app/globals.css";
import Head from "next/head";
import Dropdown from "react-bootstrap/Dropdown";
import NotificationsActiveIcon from "@mui/icons-material/NotificationsActive";
import DashboardIcon from "@mui/icons-material/Dashboard";
import Image from "next/image";
import ArrowForwardIosIcon from "@mui/icons-material/ArrowForwardIos";
import Link from "next/link";
import PersonIcon from "@mui/icons-material/Person";
import LockIcon from "@mui/icons-material/Lock";
import EmailIcon from "@mui/icons-material/Email";
import KeyIcon from "@mui/icons-material/Key";
import { useState, useEffect, useRef } from "react";
import { NavLink } from "react-bootstrap";
import { useParams, useRouter } from "next/navigation";
import KeyboardArrowRightIcon from "@mui/icons-material/KeyboardArrowRight";
import KeyboardArrowDownIcon from "@mui/icons-material/KeyboardArrowDown";
import axios from "axios";
import BaseAPI from "../BaseAPI/BaseAPI";
import "@fortawesome/fontawesome-free/css/all.css";

import Swal from "sweetalert2";
import Cookies from "js-cookie";
// import '../newcommon.css'
import "../common.css";
import { usePathname } from "next/navigation";
import { motion } from "framer-motion";
import VisibilityIcon from "@mui/icons-material/Visibility";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LS::RMS",
  description: "Generated by create next app",
  icons: {
    icon: ["/Images/favicon.ico"],

    sizes: "192x192",
    type: "image/png",
  },
};

export default function RootLayout({ children }) {
  const router = useRouter();

  const employerId = Cookies.get("employerId");
  const tokenEmployer = Cookies.get("tokenEmployer");
  const fnameEmployer = Cookies.get("fnameEmployer");
  const userType = Cookies.get("userType");

  const [logoData, setLogoData] = useState([]);
  let employer_code = Cookies.get("employer_code");

  const urlData = usePathname();
  let images = Cookies.get("employer_profile_image");
  let websiteLogo = Cookies.get("employer_website_logo");
  const toggleSidebar = () => {
    setSidebarDisplay(!sidebarDisplay);
  };

  const [sidebarDisplay, setSidebarDisplay] = useState(false);
  const [showConfigurationDropdown, setShowConfigurationDropdown] =
    useState(false);
  const handleSidebarDisplay = () => {
    setSidebarDisplay(!sidebarDisplay);
  };

  const [sidebarOpen, setSidebarOpen] = useState(false);

  const { slug } = useParams();
  useEffect(() => {
    // Check if the current URL matches any of the dropdown menu items
    if (
      urlData === "/employer/changeusername" ||
      urlData === "/employer/changepassword" ||
      urlData === "/employer/changeemail" ||
      urlData === "/employer/changeprofilepicture" ||
      urlData === "/employer/generalsetting" ||
      urlData === "/employer/website-setting" ||
      urlData === "/employer/uploadlogo" ||
      urlData === "/employer/processmanagement" ||
      urlData === "/employer/processmanagement/add" ||
      urlData === `/employer/processmanagement/edit/${slug}` ||
      urlData === "/employer/statusmanagement" ||
      urlData === "/employer/statusmanagement/addstatus" ||
      urlData === `/employer/statusmanagement/edit/${slug}` ||
      urlData === "/employer/assignusertointerview" ||
      urlData === `/employer/assignusertointerview/edit/${slug}` ||
      urlData === "/employer/assignnewprocess" ||
      urlData === `/employer/setup-expiry-time` ||
      urlData === `/employer/setup-preferences-setting` ||
      urlData === `/employer/setup-site-setting` ||
      urlData === `/employer/setup-job-application` ||
      urlData === "/employer/profile-setting"
    ) {
      setShowConfigurationDropdown(true);
    } else {
      setShowConfigurationDropdown(false);
    }
  }, [urlData]);

  const handleLogOut = async () => {
    try {
      const confirmationResult = await Swal.fire({
        title: "Logout?",
        text: "Do you want to logout?",
        icon: "question",
        showCancelButton: true,
        confirmButtonText: "Yes",
        cancelButtonText: "No",
      });
      if (confirmationResult.isConfirmed) {
        const response = await axios.post(BaseAPI + "/admin/logout", null, {
          headers: {
            "Content-Type": "application/json",
            Authorization: "Bearer" + " " + tokenEmployer,
          },
        });
        console.log(employer_code,"logout");
        Cookies.remove("tokenEmployer");
        Cookies.remove("fnameEmployer");
        router.push("/employer/login/"+employer_code);
        // window.location.reload();
        const Toast = Swal.mixin({
          toast: true,
          position: "top-end",
          showConfirmButton: false,
          timer: 3000,
          timerProgressBar: true,
          didOpen: (toast) => {
            toast.addEventListener("mouseenter", Swal.stopTimer);
            toast.addEventListener("mouseleave", Swal.resumeTimer);
          },
        });

        Toast.fire({
          icon: "success",
          title: "Logout successful",
        });
      }
    } catch (error) {
      Swal.fire({
        title: "Could not log you out",
        icon: "error",
        confirmButtonText: "Close",
      });
      console.log("Cannot logout!");
    }
  };

  const getData = async () => {
    try {
      const response = await axios.post(
        BaseAPI + "/admin/changeprofilepicture",
        null, // Pass null as the request body if not required
        {
          headers: {
            "Content-Type": "application/json",
            Authorization: "Bearer" + " " + tokenEmployer,
          },
        }
      );

      setLogoData(response.data.response.logo_path);

      Cookies.set("admin_profile_picture", response.data.response.logo_path);
    } catch (error) {
      // setLoading(false);
      console.log("Cannot get profile photo data");
    }
  };

  useEffect(() => {
    window.innerWidth < 768
      ? setSidebarDisplay(true)
      : setSidebarDisplay(false);
  }, []);

  const [isMobile, setIsMobile] = useState(false);

  const checkIsMobile = () => {
    setIsMobile(window.innerWidth <= 768); // Adjust the breakpoint as needed
  };

  useEffect(() => {
    checkIsMobile();
    window.addEventListener("resize", checkIsMobile);
    return () => {
      window.removeEventListener("resize", checkIsMobile);
    };
  }, []);

  const [notifications, setNotifications] = useState([]);
  const [showDrawer, setShowDrawer] = useState(false);
  const drawerRef = useRef(null);
  const [loading, setLoading] = useState(true);
  const toggleDrawer = () => setShowDrawer((prev) => !prev);

  const getNotifications = async () => {
    try {
      setLoading(true);
      const response = await axios.post(
        BaseAPI + `/admin/get-employer-notification`,
        { employer_id: employerId },
        {
          headers: {
            "Content-Type": "application/json",
            Authorization: "Bearer " + tokenEmployer,
          },
        }
      );
      setNotifications(response.data.response);
    } catch (error) {
      console.log(error);
    } finally {
      setLoading(false);
    }
  };
  useEffect(() => {
    getNotifications();
  }, []);

  const markAllAsRead = async () => {
    try {
      setNotifications([]); // clear after marking read
      await axios.post(BaseAPI + `/admin/mark-notification-as-read`, null, {
        headers: {
          "Content-Type": "application/json",
          Authorization: "Bearer " + tokenEmployer,
        },
      });
      setNotifications([]); // clear after marking read
      // getNotifications();
    } catch (error) {
      console.log("Error marking all as read:", error);
    } finally {
      setLoading(false);
    }
  };

  const markAsRead = async (notificationId) => {
    try {
      setLoading(true);
      await axios.post(
        BaseAPI + `/admin/mark-notification-as-read`,
        { id: notificationId },
        {
          headers: {
            "Content-Type": "application/json",
            Authorization: "Bearer " + tokenEmployer,
          },
        }
      );

      // Refresh notification list after marking as read
      getNotifications();
    } catch (error) {
      console.error("Error marking notification as read:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    getNotifications();
  }, []);

  useEffect(() => {
    if (showDrawer) {
      getNotifications();
    }
  }, [showDrawer]);

  useEffect(() => {
    window.addEventListener("profileDataLoaded", (e) => {
      let profilePicture = e.detail.profile_picture;
      let websiteLogo = e.detail.website_logo;

      // console.log("Website logo event received:", websiteLogo);
      // console.log("Profile picture event received:", profilePicture);

      Cookies.set("employer_profile_image", profilePicture);
      Cookies.set("employer_website_logo", websiteLogo);
      images = profilePicture;
      websiteLogo = websiteLogo;
    });

    
  }, []);

  const groupedNotifications = notifications.reduce((groups, notif) => {
    const date = new Date(notif.created_at).toLocaleDateString();
    if (!groups[date]) groups[date] = [];
    groups[date].push(notif);
    return groups;
  }, {});

  // Close drawer on outside click
  useEffect(() => {
    const handleClickOutside = (e) => {
      if (
        drawerRef.current &&
        !drawerRef.current.contains(e.target) &&
        !e.target.closest(".icon")
      ) {
        setShowDrawer(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);



  return (
    <html lang="en">
      <Head></Head>

      <body className={inter.className}>
        
        <div
          
          className={`adminPageLeft ${isMobile ? "mobile" : ""}`}
          style={{ display: sidebarDisplay ? "none" : "block" }}
        >
          <aside>
            <div className="sidebar   ">
              {isMobile && (
                <button
                  className="closeBtn text-dark w-100 "
                  onClick={toggleSidebar}
                >
                  <i className="fas fa-times"></i>
                </button>
              )}
              <div className="profile-name--bx flex flex-row items-center !w-full !my-2 !mb-2">
                <div className="inline-block mr-3">
                  {images !== "" ? (
                    <Image
                      src={images}
                      alt="Company Logo"
                      width={40}
                      height={40}
                      style={{ borderRadius: "50%" }}
                      className="w-12 h-12"
                    />
                  ) : (
                    <Image
                      src="/Images/adminSide/dummy-profile.png"
                      alt="Company Logo"
                      width={40}
                      height={40}
                      style={{ borderRadius: "50%" }}
                      className="w-12 h-12"
                    />
                  )}
                </div>
                <div className="text-center flex flex-col text-left">
                  {fnameEmployer && (
                    <h3>{fnameEmployer ? fnameEmployer : "User"}</h3>
                  )}
                  <h4 className="text-xs">{employerId && "Employer"}</h4>
                </div>
              </div>

              <ul className="sidebar-menu">
                <Link href="/employer/dashboard" className="sub-category">
                  <li
                    className={`sub-menu ${
                      urlData === "/employer/dashboard" ? "sidebarActive" : ""
                    }`}
                  >
                    <i className="fa-solid fa-gauge"></i>
                    <span>Dashboard</span>
                  </li>
                </Link>

                

                <Link href="/employer/managestaff" className="sub-category">
                  <li
                    className={`sub-menu ${
                      urlData === "/employer/managestaff" ||
                      urlData === "/employer/managestaff/add" ||
                      urlData === "/employer/managestaff/edit/"
                        ? "sidebarActive"
                        : ""
                    }`}
                  >
                    <i class="fa-solid fa-briefcase"></i>
                    <span>Manage Staff</span>
                  </li>
                </Link>

                <Link href="/employer/categories" className="sub-category">
                  <li
                    className={`sub-menu ${
                      urlData === "/employer/categories" ||
                      urlData === "/employer/categories/add" ||
                      urlData === "/employer/categories/edit"
                        ? "sidebarActive"
                        : ""
                    }`}
                  >
                    <i className="fa fa-sitemap"></i>
                    <span>Category List</span>
                  </li>
                </Link>
                <Link href="/employer/jobs/postjobs" className="sub-category">
                  <li
                    className={`sub-menu ${
                      urlData === "/employer/jobs/postjobs"
                        ? "sidebarActive"
                        : ""
                    }`}
                  >
                    <i className="fa fa-suitcase"></i>
                    <span>Post Job</span>
                  </li>
                </Link>
                <Link href="/employer/jobs" className="sub-category">
                  <li
                    className={`sub-menu ${
                      urlData === "/employer/jobs" ? "sidebarActive" : ""
                    }`}
                  >
                    <i className="fa fa-list-alt"></i>
                    <span>Jobs</span>
                  </li>
                </Link>

                <Link href="/employer/candidates" className="sub-category">
                  <li
                    className={`sub-menu ${
                      urlData === "/employer/candidates" ? "sidebarActive" : ""
                    }`}
                  >
                    <i className="fa fa-users"></i>
                    <span>Candidates List</span>
                  </li>
                </Link>

                <Link
                  href="/employer/interview/newassigned"
                  className="sub-category"
                >
                  <li
                    className={`sub-menu ${
                      urlData === "/employer/interview/newassigned"
                        ? "sidebarActive"
                        : ""
                    }`}
                  >
                    <i class="fa-solid fa-clipboard-question"></i>
                    <span>Interviews Assigned</span>
                  </li>
                </Link>
                <Link
                  href="/employer/selected-candidates"
                  className="sub-category"
                >
                  <li
                    className={`sub-menu ${
                      urlData === "/employer/selected-candidates"
                        ? "sidebarActive"
                        : ""
                    }`}
                  >
                    <i class="fa-solid fa-user-check"></i>
                    <span>Selected Candidates</span>
                  </li>
                </Link>
                <Link href="/employer/resume-parser" className="sub-category">
                  <li
                    className={`sub-menu ${
                      urlData === "/employer/resume-parser"
                        ? "sidebarActive"
                        : ""
                    }`}
                  >
                    <i class="fa-solid fa-clipboard-check"></i>
                    <span>Resume Parser</span>
                  </li>
                </Link>

                <Link href="/employer/skills" className="sub-category">
                  <li
                    className={`sub-menu ${
                      urlData === "/employer/skills" ||
                      urlData === "/employer/addskills" ||
                      urlData === "/employer/edit"
                        ? "sidebarActive"
                        : ""
                    }`}
                  >
                    <i class="fa-solid fa-atom"></i>
                    <span>Skill List</span>
                  </li>
                </Link>

                <Link
                  href="/employer/qualificationlist"
                  className="sub-category"
                >
                  <li
                    className={`sub-menu ${
                      urlData === "/employer/qualificationlist" ||
                      urlData === "/employer/addqualification" ||
                      urlData === "/employer/updatequalification"
                        ? "sidebarActive"
                        : ""
                    }`}
                  >
                    <i class="fa-solid fa-graduation-cap"></i>
                    <span>Qualification List</span>
                  </li>
                </Link>

                <Link href="/employer/industry" className="sub-category">
                  <li
                    className={`sub-menu ${
                      urlData === "/employer/industry" ||
                      urlData === "/employer/industry/add" ||
                      urlData === "/employer/updateindustry"
                        ? "sidebarActive"
                        : ""
                    }`}
                  >
                    <i class="fa-solid fa-industry"></i>
                    <span>Industry List</span>
                  </li>
                </Link>

                <Link href="/employer/designation" className="sub-category">
                  <li
                    className={`sub-menu ${
                      urlData === "/employer/designation" ||
                      urlData === "/employer/designation/add" ||
                      urlData === "/employer/edit"
                        ? "sidebarActive"
                        : ""
                    }`}
                  >
                    <i class="fa-solid fa-briefcase"></i>
                    <span>Designation List</span>
                  </li>
                </Link>

                <Link href="/employer/currencies" className="sub-category">
                  <li
                    className={`sub-menu ${
                      urlData === "/employer/currencies" ||
                      urlData === "/employer/currencies/add" ||
                      urlData === "/employer/currencies/edit"
                        ? "sidebarActive"
                        : ""
                    }`}
                  >
                    <i class="fa-solid fa-coins"></i>
                    <span>Currency List</span>
                  </li>
                </Link>

                <Link href="/employer/email-templates" className="sub-category">
                  <li
                    className={`sub-menu ${
                      urlData === "/employer/email-templates" ||
                      urlData === "/employer/email-templates/add" ||
                      urlData === "/employer/email-templates/edit"
                        ? "sidebarActive"
                        : ""
                    }`}
                  >
                    <i class="fa-solid fa-envelope"></i>
                    <span>Email Templates</span>
                  </li>
                </Link>

                <li
                  className={`sub-menu ${
                    urlData === "/employer/changeusername" ||
                    urlData === "/employer/changepassword" ||
                    urlData === "/employer/changeemail" ||
                    urlData === "/employer/changeprofilepicture" ||
                    urlData === "/employer/generalsetting" ||
                    urlData === "/employer/website-setting" ||
                    urlData === "/employer/uploadLogo" ||
                    urlData === "/employer/interviewprocess" ||
                    urlData === "/employer/addinterviewprocess" ||
                    urlData === "/employer/updateinterviewprocess/1" ||
                    urlData === "/employer/statusmanagement" ||
                    urlData === "/employer/addinterviewstatus" ||
                    urlData === "/employer/updateinterviewstatus" ||
                    urlData === "/employer/assignusertointerview" ||
                    urlData === "/employer/profile-setting"
                      ? "sidebarActive"
                      : ""
                  }`}
                  onClick={() =>
                    setShowConfigurationDropdown(!showConfigurationDropdown)
                  }
                >
                  <Link
                    href=""
                    className={`sub-category 
                    `}
                  >
                    <div className="eachMenuItem">
                      <div className="menuLeftSection">
                        <i className="fa fa-gears"></i>
                        <span>Configuration </span>
                      </div>

                      {showConfigurationDropdown ? (
                        <div id="icon2">
                          <KeyboardArrowDownIcon />
                        </div>
                      ) : (
                        <div id="icon2">
                          <KeyboardArrowRightIcon />
                        </div>
                      )}
                    </div>
                  </Link>
                </li>
                <div
                  className={`dropdown ${
                    showConfigurationDropdown ? "open" : ""
                  }`}
                >
                  <div className="dropdown-item">
                    <ul className="SidebarListInternal">
                      
                      {/* <Link href="/employer/generalsetting">
                        <li
                          className={`row ${
                            urlData === "/employer/generalsetting" ||
                            urlData === "/employer/changeusername" ||
                            urlData === "/employer/changepassword" ||
                            urlData === "/employer/changeemail" ||
                            urlData === "/employer/changeprofilepicture" ||
                            urlData === "/employer/uploadlogo"
                              ? "active"
                              : ""
                          }`}
                        >
                          <p
                            id="title"
                            className={
                              urlData === "/employer/generalsetting" ||
                              urlData === "/employer/changeusername" ||
                              urlData === "/employer/changepassword" ||
                              urlData === "/employer/changeemail" ||
                              urlData === "/employer/changeprofilepicture" ||
                              urlData === "/employer/uploadlogo"
                                ? "sidebarDropdownActive"
                                : ""
                            }
                          >
                            General Setting
                          </p>
                        </li>
                      </Link> */}
                      <Link href="/employer/website-setting">
                        <li
                          className={`row ${
                            urlData === "/employer/website-setting" ||
                            urlData === "/employer/setup-expiry-time" ||
                            urlData === "/employer/setup-preferences-setting" ||
                            urlData === "/employer/setup-site-setting" ||
                            urlData === "/employer/setup-job-application"
                              ? "active"
                              : ""
                          }`}
                        >
                          <p
                            id="title"
                            className={
                              urlData === "/employer/website-setting" ||
                              urlData === "/employer/setup-expiry-time" ||
                              urlData ===
                                "/employer/setup-preferences-setting" ||
                              urlData === "/employer/setup-site-setting" ||
                              urlData === "/employer/setup-job-application"
                                ? "sidebarDropdownActive"
                                : ""
                            }
                          >
                            Website Setting
                          </p>
                        </li>
                      </Link>

                     

                      <Link href="/employer/profile-setting">
                        <li
                          className={`row ${
                            urlData === "/employer/profile-setting"
                            
                              ? "active"
                              : ""
                          }`}
                        >
                          <p
                            id="title"
                            className={
                              urlData === "/employer/profile-setting"
                              
                                ? "sidebarDropdownActive"
                                : ""
                            }
                          >
                            Profile Settings
                          </p>
                        </li>
                      </Link>

                      <Link href="/employer/processmanagement">
                        <li
                          className={`row ${
                            urlData === "/employer/interviewprocess" ||
                            urlData === "/employer/processmanagement/add" ||
                            urlData ===
                              `/employer/processmanagement/edit/${slug}`
                              ? "active"
                              : ""
                          }`}
                        >
                          <p
                            id="title"
                            className={
                              urlData === "/employer/processmanagement" ||
                              urlData === "/employer/processmanagement/add" ||
                              urlData ===
                                `/employer/processmanagement/edit/${slug}`
                                ? "sidebarDropdownActive"
                                : ""
                            }
                          >
                            Interview Process
                          </p>
                        </li>
                      </Link>

                      <Link href="/employer/statusmanagement">
                        <li
                          className={`row ${
                            urlData === "/employer/statusmanagement" ||
                            urlData ===
                              "/employer/statusmanagement/addstatus" ||
                            urlData ===
                              `/employer/statusmanagement/edit/${slug}`
                              ? "active"
                              : ""
                          }`}
                        >
                          <p
                            id="title"
                            className={
                              urlData === "/employer/statusmanagement" ||
                              urlData ===
                                "/employer/statusmanagement/addstatus" ||
                              urlData ===
                                `/employer/statusmanagement/edit/${slug}`
                                ? "sidebarDropdownActive"
                                : ""
                            }
                          >
                            Status Management
                          </p>
                        </li>
                      </Link>
                      <Link href="/employer/assignusertointerview">
                        <li
                          className={`row ${
                            urlData === "/employer/assignusertointerview" ||
                            urlData === "/employer/assignnewprocess" ||
                            urlData ===
                              `/employer/assignusertointerview/edit/${slug}`
                              ? "active"
                              : ""
                          }`}
                        >
                          <p
                            id="title"
                            className={
                              urlData === "/employer/assignusertointerview" ||
                              urlData === "/employer/assignnewprocess" ||
                              urlData ===
                                `/employer/assignusertointerview/edit/${slug}`
                                ? "sidebarDropdownActive"
                                : ""
                            }
                          >
                            Assign Users to the interview
                          </p>
                        </li>
                      </Link>
                    </ul>
                  </div>
                </div>

                <Link href="" className={`sub-category`} onClick={handleLogOut}>
                  <li className="sub-menu">
                    <i class="fas fa-sign-out-alt"></i>
                    <span>Logout</span>
                  </li>
                </Link>
              </ul>
            </div>
          </aside>
        </div>
        {/* </motion.div>
  )}
</AnimatePresence> */}
        <div
          className="adminPageRight backgroundColor"
          style={{ paddingLeft: sidebarDisplay ? "0" : "266px" }}
        >
          <nav>
            <div className="adminNavbar">
              <div className="leftSide" onClick={handleSidebarDisplay}>
                <DashboardIcon />
                <span className="navLogo">
                  {websiteLogo !== "" && (
                    <Image
                      src={websiteLogo}
                      alt="logo"
                      width={120}
                      height={90}
                      className="object-contain w-[120px] h-[35px]"
                    />
                  )}
                </span>
              </div>
              <div className="rightSide">
                <div
                  className="icon relative cursor-pointer"
                  onClick={toggleDrawer}
                >
                  <NotificationsActiveIcon />
                  {notifications.length > 0 && (
                    <span className="absolute -top-1 -right-[0px] bg-red-600 text-white text-xs font-bold px-1.5 py-0.5 rounded-full shadow-md animate-bounce">
                      {notifications.length > 9 ? "9+" : notifications.length}
                    </span>
                  )}
                </div>
                <div className="userIcon flex items-center gap-2">
                  

                  <Dropdown>
                    <Dropdown.Toggle className="bg-white text-black">
                      <ArrowForwardIosIcon fontSize="smaller" />
                    </Dropdown.Toggle>
                    <Dropdown.Menu>
                      <Dropdown.Item>
                        <div className="">
                          <ul
                            className=" custom-dropdown-menu"
                            aria-labelledby="dropdownMenuButton1"
                          >
                            <li className=" text-black">
                              <Link href="/employer/changeusername">
                                <PersonIcon />
                                <span>Change Username</span>
                              </Link>
                            </li>
                            <li className="">
                              <Link href="/employer/changepassword">
                                <LockIcon />
                                <span>Change Password</span>
                              </Link>
                            </li>
                            <li className="">
                              <Link href="/employer/changeemail">
                                <EmailIcon />
                                <span>Change Email</span>
                              </Link>
                            </li>
                            <li className="logOutButton" onClick={handleLogOut}>
                              <KeyIcon />
                              Logout
                            </li>
                          </ul>
                        </div>
                      </Dropdown.Item>
                    </Dropdown.Menu>
                  </Dropdown>
                </div>
              </div>
            </div>
          </nav>

          {/* Notification Drawer */}
          {/* 📦 Notification Drawer */}
          {showDrawer && (
            <div
              ref={drawerRef}
              className="fixed top-16 right-0 w-110 h-full bg-white shadow-lg z-50 transition-transform transform animate-slide-in overflow-y-auto p-4 min-w-[657px]"
            >
              <div className="flex justify-between items-center mb-2">
                <h3 className="text-lg font-semibold">Notifications</h3>
                <button
                  onClick={toggleDrawer}
                  className="text-gray-600 text-xl pointer"
                >
                  ✕
                </button>
              </div>
              <hr />

              {/* Mark All As Read */}
              {notifications.length > 0 && (
                <div className="flex justify-end mb-4">
                  <button
                    className="text-sm pt-2 text-gray-400 underline hover:text-blue-800 transition"
                    onClick={markAllAsRead}
                  >
                    Mark all as read
                  </button>
                </div>
              )}

              {/* Notification Content */}
              <div className="min-h-[200px] w-full">
                {loading ? (
                  <div className="flex justify-center items-center min-h-[200px]">
                    <span className="text-sm text-gray-400 animate-pulse">
                      Loading notifications...
                    </span>
                  </div>
                ) : notifications.length > 0 ? (
                  Object.keys(groupedNotifications).map((date) => (
                    <div key={date}>
                      <h5 className="text-xs text-gray-500 mb-2 mt-4">
                        {date}
                      </h5>
                      <ul className="space-y-4">
                        {groupedNotifications[date].map((notification, idx) => (
                          <li
                            key={idx}
                            className={`border-b rounded p-2 flex justify-between items-center ${
                              notification.mark_as_read === "0"
                                ? "bg-gray-100"
                                : ""
                            }`}
                          >
                            <div className="flex-1 flex items-start">
                              {notification.mark_as_read === "0" && (
                                <span className="inline-block w-2 h-2 bg-orange-500 rounded-full mr-2 mt-1.5"></span>
                              )}
                              <div>
                                <h4 className="font-bold text-sm">
                                  {notification.notification_title}
                                </h4>
                                <p className="text-gray-600 text-sm">
                                  {notification.notification_text}
                                </p>
                                <p className="text-xs text-gray-400 mt-1">
                                  {new Date(
                                    notification.created_at
                                  ).toLocaleTimeString()}
                                </p>
                              </div>
                            </div>
                            <button
                              onClick={() => markAsRead(notification.id)}
                              className="ml-3 text-blue-600 hover:text-blue-800 transition flex items-center justify-center"
                              title="Mark as Read"
                            >
                              <VisibilityIcon fontSize="small" />
                            </button>
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))
                ) : (
                  <div className="flex items-center justify-center min-h-[200px] text-sm text-gray-500">
                    No notifications
                  </div>
                )}
              </div>
            </div>
          )}
          {children}
        </div>
      </body>
    </html>
  );
}
