import { Inter } from "next/font/google";
import "../../app/globals.css";
import Head from "next/head";
import Dropdown from "react-bootstrap/Dropdown";
import NotificationsActiveIcon from "@mui/icons-material/NotificationsActive";
import DashboardIcon from "@mui/icons-material/Dashboard";
import Image from "next/image";
import ArrowForwardIosIcon from "@mui/icons-material/ArrowForwardIos";
import Link from "next/link";
import PersonIcon from "@mui/icons-material/Person";
import LockIcon from "@mui/icons-material/Lock";
import EmailIcon from "@mui/icons-material/Email";
import KeyIcon from "@mui/icons-material/Key";
import { useState, useEffect, useRef } from "react";
import { NavLink } from "react-bootstrap";
import { useParams, useRouter } from "next/navigation";
import KeyboardArrowRightIcon from "@mui/icons-material/KeyboardArrowRight";
import KeyboardArrowDownIcon from "@mui/icons-material/KeyboardArrowDown";
import axios from "axios";
import BaseAPI from "../BaseAPI/BaseAPI";
import "@fortawesome/fontawesome-free/css/all.css";
import Swal from "sweetalert2";
import Cookies from "js-cookie";
import "../common.css";
import { usePathname } from "next/navigation";
import VisibilityIcon from "@mui/icons-material/Visibility";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LS::RMS",
  description: "Generated by create next app",
  icons: {
    icon: ["/Images/favicon.ico"],

    sizes: "192x192",
    type: "image/png",
  },
};

export default function RootLayout({ children }) {
  const router = useRouter();
  const adminId = Cookies.get("adminId");
  const staffId = Cookies.get("staffId");
  const tokenStaff = Cookies.get("tokenStaff");
  const fnameStaff = Cookies.get("fnameStaff");
  const userType = Cookies.get("userType");
  const access = Cookies.get("access");
  const [logoData, setLogoData] = useState([]);
  const urlData = usePathname();
  const [sidebarDisplay, setSidebarDisplay] = useState(false);
  const [showConfigurationDropdown, setShowConfigurationDropdown] =
    useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const { slug } = useParams();
  const [isMobile, setIsMobile] = useState(false);
  const [userAccess, setUserAccess] = useState({});
  const [notifications, setNotifications] = useState([]);
  const [showDrawer, setShowDrawer] = useState(false);
  const [loading, setLoading] = useState(true);
  const [showNotificationPopup, setShowNotificationPopup] = useState(false);
  const [unreadNotificationCount, setUnreadNotificationCount] = useState(0);
  const drawerRef = useRef(null);
  let websiteLogo = Cookies.get("employer_website_logo");
  let images = Cookies.get("staff_profile_image");
  let employer_code = Cookies.get("employer_code");

  const toggleSidebar = () => setSidebarDisplay(!sidebarDisplay);
  const handleSidebarDisplay = () => setSidebarDisplay(!sidebarDisplay);
  const toggleDrawer = () => setShowDrawer((prev) => !prev);

  useEffect(() => {
    if (
      urlData === "/staff/changeusername" ||
      urlData === "/staff/changepassword" ||
      urlData === "/staff/changeemail" ||
      urlData === "/staff/changeprofilepicture" ||
      urlData === "/staff/generalsetting" ||
      urlData === "/staff/uploadlogo" ||
      urlData === "/staff/processmanagement" ||
      urlData === "/staff/processmanagement/add" ||
      urlData === `/staff/processmanagement/edit/${slug}` ||
      urlData === "/staff/statusmanagement" ||
      urlData === "/staff/statusmanagement/addstatus" ||
      urlData === `/staff/statusmanagement/edit/${slug}` ||
      urlData === "/staff/assignusertointerview" ||
      urlData === `/staff/assignusertointerview/edit/${slug}` ||
      urlData === "/staff/assignnewprocess" ||
      urlData === `/staff/profile-settings`
    ) {
      setShowConfigurationDropdown(true);
    } else {
      setShowConfigurationDropdown(false);
    }
  }, [urlData, slug]);

  const handleLogOut = async () => {
    try {
      const confirmationResult = await Swal.fire({
        title: "Logout?",
        text: "Do you want to logout?",
        icon: "question",
        showCancelButton: true,
        confirmButtonText: "Yes",
        cancelButtonText: "No",
      });
      if (confirmationResult.isConfirmed) {
        const response = await axios.post(BaseAPI + "/admin/logout", null, {
          headers: {
            "Content-Type": "application/json",
            Authorization: "Bearer " + tokenStaff,
          },
        });
        Cookies.remove("tokenStaff");
        Cookies.remove("fnameStaff");
        router.push("/staff/login/"+employer_code);
        // window.location.reload();
        const Toast = Swal.mixin({
          toast: true,
          position: "top-end",
          showConfirmButton: false,
          timer: 3000,
          timerProgressBar: true,
          didOpen: (toast) => {
            toast.addEventListener("mouseenter", Swal.stopTimer);
            toast.addEventListener("mouseleave", Swal.resumeTimer);
          },
        });
        Toast.fire({
          icon: "success",
          title: "Logout successful",
        });
      }
    } catch (error) {
      Swal.fire({
        title: "Could not log you out",
        icon: "error",
        confirmButtonText: "Close",
      });
      console.log("Cannot logout!");
    }
  };

  const getData = async () => {
    try {
      const response = await axios.post(
        BaseAPI + "/admin/changeprofilepicture",
        null,
        {
          headers: {
            "Content-Type": "application/json",
            Authorization: "Bearer " + tokenStaff,
          },
        }
      );
      setLogoData(response.data.response.logo_path);
      Cookies.set("admin_profile_picture", response.data.response.logo_path);
    } catch (error) {
      console.log("Cannot get profile photo data");
    }
  };

  useEffect(() => {
    window.innerWidth < 768
      ? setSidebarDisplay(true)
      : setSidebarDisplay(false);
  }, []);

  const checkIsMobile = () => {
    setIsMobile(window.innerWidth <= 768);
  };

  useEffect(() => {
    checkIsMobile();
    window.addEventListener("resize", checkIsMobile);
    return () => window.removeEventListener("resize", checkIsMobile);
  }, []);

  useEffect(() => {
    const access = Cookies.get("access");
    if (access && access !== "null" && access !== "undefined") {
      setUserAccess(JSON.parse(access));
    } else {
      setUserAccess({});
    }
  }, []);

  const getNotifications = async () => {
    try {
      setLoading(true);
      const response = await axios.post(
        BaseAPI + `/admin/get-staff-notification`,
        { staff_id: staffId },
        {
          headers: {
            "Content-Type": "application/json",
            Authorization: "Bearer " + tokenStaff,
          },
        }
      );
      const notificationData = response.data.response;
      setNotifications(notificationData);
      const unreadCount = notificationData.filter(
        (notif) => notif.mark_as_read === "0"
      ).length;
      setUnreadNotificationCount(unreadCount);
    } catch (error) {
      console.log(error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    getNotifications();
  }, []);

  useEffect(() => {
    if (showDrawer) {
      getNotifications();
    }
  }, [showDrawer]);

  // Show popup when landing on dashboard with unread notifications
  useEffect(() => {
    if (
      urlData === "/staff/dashboard" &&
      unreadNotificationCount > 0 &&
      !showDrawer
    ) {
      setShowNotificationPopup(true);
      const timer = setTimeout(() => {
        setShowNotificationPopup(false);
      }, 5000); // Hide after 5 seconds
      return () => clearTimeout(timer);
    }
  }, [urlData, unreadNotificationCount]);

  const markAllAsRead = async () => {
    try {
      await axios.post(BaseAPI + `/admin/mark-notification-as-read`, null, {
        headers: {
          "Content-Type": "application/json",
          Authorization: "Bearer " + tokenStaff,
        },
      });
      setNotifications([]);
      setUnreadNotificationCount(0);
    } catch (error) {
      console.log("Error marking all as read:", error);
    } finally {
      setLoading(false);
    }
  };

  const markAsRead = async (notificationId) => {
    try {
      setLoading(true);
      await axios.post(
        BaseAPI + `/admin/mark-notification-as-read`,
        { id: notificationId },
        {
          headers: {
            "Content-Type": "application/json",
            Authorization: "Bearer " + tokenStaff,
          },
        }
      );
      getNotifications();
    } catch (error) {
      console.error("Error marking notification as read:", error);
    } finally {
      setLoading(false);
    }
  };

  const groupedNotifications = notifications.reduce((groups, notif) => {
    const date = new Date(notif.created_at).toLocaleDateString();
    if (!groups[date]) groups[date] = [];
    groups[date].push(notif);
    return groups;
  }, {});

  useEffect(() => {
    const handleClickOutside = (e) => {
      if (
        drawerRef.current &&
        !drawerRef.current.contains(e.target) &&
        !e.target.closest(".icon")
      ) {
        setShowDrawer(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  useEffect(() => {
    window.addEventListener("profileDataLoaded", (e) => {
      let profilePicture = e.detail.profile_picture;
      let websiteLogo = e.detail.website_logo;

      Cookies.set("staff_profile_image", profilePicture);
      // Cookies.set("employer_website_logo", websiteLogo);
      images = profilePicture;
      // websiteLogo = websiteLogo;
    });
  }, []);

  return (
    <html lang="en">
      <Head></Head>
      <body className={inter.className}>
        <div
          className={`adminPageLeft ${isMobile ? "mobile" : ""}`}
          style={{ display: sidebarDisplay ? "none" : "block" }}
        >
          <aside>
            <div className="sidebar   ">
              {isMobile && (
                <button
                  className="closeBtn text-dark w-100 "
                  onClick={toggleSidebar}
                >
                  <i className="fas fa-times"></i>
                </button>
              )}
              <div className="profile-name--bx flex flex-row items-center !w-full !my-2 !mb-2">
                <div className="inline-block mr-3">
                  {images !== "" ? (
                    <Image
                      src={images}
                      alt="Company Logo"
                      width={40}
                      height={40}
                      style={{ borderRadius: "50%" }}
                      className="w-12 h-12"
                    />
                  ) : (
                    <Image
                      src="/Images/adminSide/dummy-profile.png"
                      alt="Company Logo"
                      width={40}
                      height={40}
                      style={{ borderRadius: "50%" }}
                      className="w-12 h-12"
                    />
                  )}
                </div>
                <div className="text-center flex flex-col text-left">
                  {fnameStaff && <h3>{fnameStaff ? fnameStaff : "User"}</h3>}

                  <h4 className="text-xs">Staff</h4>
                </div>
              </div>

              <ul className="sidebar-menu">
                <Link href="/staff/dashboard" className="sub-category">
                  <li
                    className={`sub-menu ${
                      urlData === "/staff/dashboard" ? "sidebarActive" : ""
                    }`}
                  >
                    <i className="fa-solid fa-gauge"></i>
                    <span>Dashboard</span>
                  </li>
                </Link>

                <Link
                  href="/staff/interview/newassigned"
                  className="sub-category"
                >
                  <li
                    className={`sub-menu ${
                      urlData === "/staff/interview/newassigned"
                        ? "sidebarActive"
                        : ""
                    }`}
                  >
                    <i class="fa-solid fa-clipboard-question"></i>
                    <span>Interviews Assigned</span>
                  </li>
                </Link>
                {userAccess[0]?.Module === 1 && (
                  <Link href="/staff/jobs" className="sub-category">
                    <li
                      className={`sub-menu ${
                        urlData === "/staff/jobs" ? "sidebarActive" : ""
                      }`}
                    >
                      <i className="fa fa-list-alt"></i>
                      <span>Jobs</span>
                    </li>
                  </Link>
                )}
                {userAccess[1]?.Module === 1 && (
                  <Link href="/staff/candidates" className="sub-category">
                    <li
                      className={`sub-menu ${
                        urlData === "/staff/candidates" ? "sidebarActive" : ""
                      }`}
                    >
                      <i className="fa fa-users"></i>
                      <span>Candidates List</span>
                    </li>
                  </Link>
                )}
                {userAccess[14]?.Module === 1 && (
                  <Link
                    href="/staff/interview-list/newassigned"
                    className="sub-category"
                  >
                    <li
                      className={`sub-menu ${
                        urlData === "/staff/interview-list/newassigned"
                          ? "sidebarActive"
                          : ""
                      }`}
                    >
                      <i class="fa-solid fa-clipboard-question"></i>
                      <span>Interview List</span>
                    </li>
                  </Link>
                )}
                {userAccess[15]?.Module === 1 && (
                  <Link
                    href="/staff/selected-candidates"
                    className="sub-category"
                  >
                    <li
                      className={`sub-menu ${
                        urlData === "/staff/selected-candidates"
                          ? "sidebarActive"
                          : ""
                      }`}
                    >
                      <i class="fa-solid fa-user-check"></i>
                      <span>Selected Candidates</span>
                    </li>
                  </Link>
                )}

                {userAccess[2]?.Module === 1 && (
                  <Link href="/staff/categories" className="sub-category">
                    <li
                      className={`sub-menu ${
                        urlData === "/staff/categories" ||
                        urlData === "/staff/categories/add" ||
                        urlData === "/staff/categories/edit"
                          ? "sidebarActive"
                          : ""
                      }`}
                    >
                      <i className="fa fa-sitemap"></i>
                      <span>Category List</span>
                    </li>
                  </Link>
                )}
                {userAccess[3]?.Module === 1 && (
                  <Link href="/staff/skills" className="sub-category">
                    <li
                      className={`sub-menu ${
                        urlData === "/staff/skills" ||
                        urlData === "/staff/addskills" ||
                        urlData === "/staff/edit"
                          ? "sidebarActive"
                          : ""
                      }`}
                    >
                      <i class="fa-solid fa-atom"></i> <span>Skill List</span>
                    </li>
                  </Link>
                )}
                {userAccess[4]?.Module === 1 && (
                  <Link
                    href="/staff/qualificationlist"
                    className="sub-category"
                  >
                    <li
                      className={`sub-menu ${
                        urlData === "/staff/qualificationlist" ||
                        urlData === "/staff/addqualification" ||
                        urlData === "/staff/updatequalification"
                          ? "sidebarActive"
                          : ""
                      }`}
                    >
                      <i class="fa-solid fa-graduation-cap"></i>
                      <span>Qualification List</span>
                    </li>
                  </Link>
                )}
                {userAccess[5]?.Module === 1 && (
                  <Link href="/staff/industry" className="sub-category">
                    <li
                      className={`sub-menu ${
                        urlData === "/staff/industry" ||
                        urlData === "/staff/industry/add" ||
                        urlData === "/staff/updateindustry"
                          ? "sidebarActive"
                          : ""
                      }`}
                    >
                      <i class="fa-solid fa-industry"></i>
                      <span>Industry List</span>
                    </li>
                  </Link>
                )}

                {userAccess[6]?.Module === 1 && (
                  <Link href="/staff/designation" className="sub-category">
                    <li
                      className={`sub-menu ${
                        urlData === "/staff/designation" ||
                        urlData === "/staff/designation/add" ||
                        urlData === "/staff/edit"
                          ? "sidebarActive"
                          : ""
                      }`}
                    >
                      <i class="fa-solid fa-briefcase"></i>
                      <span>Designation List</span>
                    </li>
                  </Link>
                )}

                {userAccess[7]?.Module === 1 && (
                  <Link href="/staff/currencies" className="sub-category">
                    <li
                      className={`sub-menu ${
                        urlData === "/staff/currencies" ||
                        urlData === "/staff/currencies/add" ||
                        urlData === "/staff/currencies/edit"
                          ? "sidebarActive"
                          : ""
                      }`}
                    >
                      <i class="fa-solid fa-coins"></i>
                      <span>Currency List</span>
                    </li>
                  </Link>
                )}
                {userAccess[8]?.Module === 1 && (
                  <Link href="/staff/email-templates" className="sub-category">
                    <li
                      className={`sub-menu ${
                        urlData === "/staff/email-templates"
                          ? "sidebarActive"
                          : ""
                      }`}
                    >
                      <i class="fa-solid fa-envelope"></i>
                      <span>Email Template</span>
                    </li>
                  </Link>
                )}
                {userAccess[9]?.Module === 1 && (
                  <Link href="/staff/resume-parser" className="sub-category">
                    <li
                      className={`sub-menu ${
                        urlData === "/staff/resume-parser"
                          ? "sidebarActive"
                          : ""
                      }`}
                    >
                      <i class="fa-solid fa-clipboard-check"></i>
                      <span>Resume Parser</span>
                    </li>
                  </Link>
                )}

                <li
                  className={`sub-menu ${
                    urlData === "/staff/changeusername" ||
                    urlData === "/staff/changepassword" ||
                    urlData === "/staff/changeemail" ||
                    urlData === "/staff/changeprofilepicture" ||
                    urlData === "/staff/generalsetting" ||
                    urlData === "/employer/uploadLogo" ||
                    urlData === "/employer/interviewprocess" ||
                    urlData === "/employer/addinterviewprocess" ||
                    urlData === "/employer/updateinterviewprocess/1" ||
                    urlData === "/employer/statusmanagement" ||
                    urlData === "/employer/addinterviewstatus" ||
                    urlData === "/employer/updateinterviewstatus" ||
                    urlData === "/employer/assignusertointerview"
                      ? "sidebarActive"
                      : ""
                  }`}
                  onClick={() =>
                    setShowConfigurationDropdown(!showConfigurationDropdown)
                  }
                >
                  <Link
                    href=""
                    className={`sub-category 
                    `}
                  >
                    <div className="eachMenuItem">
                      <div className="menuLeftSection">
                        <i className="fa fa-gears"></i>
                        <span>Configuration </span>
                      </div>

                      {showConfigurationDropdown ? (
                        <div id="icon2">
                          <KeyboardArrowDownIcon />
                        </div>
                      ) : (
                        <div id="icon2">
                          <KeyboardArrowRightIcon />
                        </div>
                      )}
                    </div>
                  </Link>
                </li>
                <div
                  className={`dropdown ${
                    showConfigurationDropdown ? "open" : ""
                  }`}
                >
                  <div className="dropdown-item">
                    <ul className="SidebarListInternal">
                      <Link href="/staff/profile-setting">
                        <li
                          className={`row ${
                            urlData === "/staff/profile-setting" ? "active" : ""
                          }`}
                        >
                          <p
                            id="title"
                            className={
                              urlData === "/staff/profile-setting"
                                ? "sidebarDropdownActive"
                                : ""
                            }
                          >
                            Profile Settings
                          </p>
                        </li>
                      </Link>

                      {userAccess[10]?.Module === 1 && (
                        <>
                          {userAccess[10]?.Change_Website_Logo === 1 && (
                            <Link href="/staff/uploadlogo">
                              <li
                                className={`row ${
                                  urlData === "/staff/uploadlogo"
                                    ? "active"
                                    : ""
                                }`}
                              >
                                <p
                                  id="title"
                                  className={
                                    urlData === "/staff/uploadlogo"
                                      ? "sidebarDropdownActive"
                                      : ""
                                  }
                                >
                                  Change Website Logo
                                </p>
                              </li>
                            </Link>
                          )}

                          {userAccess[11]?.Module === 1 && (
                            <Link href="/staff/processmanagement">
                              <li
                                className={`row ${
                                  urlData === "/staff/interviewprocess" ||
                                  urlData === "/staff/processmanagement/add" ||
                                  urlData ===
                                    `/staff/processmanagement/edit/${slug}`
                                    ? "active"
                                    : ""
                                }`}
                              >
                                <p
                                  id="title"
                                  className={
                                    urlData === "/staff/processmanagement" ||
                                    urlData ===
                                      "/staff/processmanagement/add" ||
                                    urlData ===
                                      `/staff/processmanagement/edit/${slug}`
                                      ? "sidebarDropdownActive"
                                      : ""
                                  }
                                >
                                  Interview Process
                                </p>
                              </li>
                            </Link>
                          )}
                          {userAccess[10]?.Status_Management === 1 && (
                            <NavLink href="/staff/statusmanagement">
                              <li
                                className={`row ${
                                  urlData === "/staff/statusmanagement" ||
                                  urlData ===
                                    "/staff/statusmanagement/addstatus" ||
                                  urlData ===
                                    `/staff/statusmanagement/edit/${slug}`
                                    ? "active"
                                    : ""
                                }`}
                              >
                                <p
                                  id="title"
                                  className={
                                    urlData === "/staff/statusmanagement" ||
                                    urlData ===
                                      "/staff/statusmanagement/addstatus" ||
                                    urlData ===
                                      `/staff/statusmanagement/edit/${slug}`
                                      ? "sidebarDropdownActive"
                                      : ""
                                  }
                                >
                                  Status Management
                                </p>
                              </li>
                            </NavLink>
                          )}

                          {userAccess[13]?.Module === 1 && (
                            <NavLink href="/staff/assignusertointerview">
                              <li
                                className={`row ${
                                  urlData === "/staff/assignusertointerview" ||
                                  urlData === "/staff/assignnewprocess" ||
                                  urlData ===
                                    `/staff/assignusertointerview/edit/${slug}`
                                    ? "active"
                                    : ""
                                }`}
                              >
                                <p
                                  id="title"
                                  className={
                                    urlData ===
                                      "/staff/assignusertointerview" ||
                                    urlData === "/staff/assignnewprocess" ||
                                    urlData ===
                                      `/staff/assignusertointerview/edit/${slug}`
                                      ? "sidebarDropdownActive"
                                      : ""
                                  }
                                >
                                  Assign Users to the interview
                                </p>
                              </li>
                            </NavLink>
                          )}
                        </>
                      )}
                    </ul>
                  </div>
                </div>

                <Link href="" className={`sub-category`} onClick={handleLogOut}>
                  <li className="sub-menu">
                    <i class="fas fa-sign-out-alt"></i>
                    <span>Logout</span>
                  </li>
                </Link>
              </ul>
            </div>
          </aside>
        </div>

        <div
          className="adminPageRight backgroundColor"
          style={{ paddingLeft: sidebarDisplay ? "0" : "266px" }}
        >
          <nav>
            <div className="adminNavbar">
              <div className="leftSide" onClick={handleSidebarDisplay}>
                <DashboardIcon />
                <span className="navLogo">
                  {websiteLogo !== "" && (
                    <Image
                      src={websiteLogo}
                      alt="logo"
                      width={120}
                      height={90}
                      className="object-contain w-[120px] h-[35px]"
                    />
                  )}
                </span>
              </div>
              <div className="rightSide gap-0 relative">
                <div
                  className="icon relative cursor-pointer"
                  onClick={toggleDrawer}
                >
                  <NotificationsActiveIcon />
                  {notifications.length > 0 && (
                    <span className="absolute -top-1 -right-[0px] bg-red-600 text-white text-xs font-bold px-1.5 py-0.5 rounded-full shadow-md animate-bounce">
                      {notifications.length > 9 ? "9+" : notifications.length}
                    </span>
                  )}
                </div>
                {showNotificationPopup && (
                  <div className="!w-[245px] absolute top-12 right-6 bg-white text-gray-800 p-4 rounded-lg shadow-lg z-50 animate-slide-in">
                    <p className="text-sm font-semibold">
                      You have {unreadNotificationCount} new notification
                      {unreadNotificationCount > 1 ? "s" : ""}!
                    </p>
                    <button
                      onClick={() => setShowNotificationPopup(false)}
                      className="mt-2 text-blue-600 hover:text-blue-800 text-sm"
                    >
                      Dismiss
                    </button>
                  </div>
                )}
                <div className="userIcon flex items-center gap-2">
                  {/* {images ? (
                    <Image
                      src={images}
                      alt="Company Logo"
                      width={180}
                      height={180}
                      style={{ borderRadius: "50%" }}
                    />
                  ) : (
                    <Image
                      src="/Images/adminSide/dummy-profile.png"
                      alt="Company Logo"
                      width={180}
                      height={180}
                      style={{ borderRadius: "50%" }}
                    />
                  )} */}
                  <Dropdown>
                    <Dropdown.Toggle className="bg-white text-black">
                      <ArrowForwardIosIcon fontSize="smaller" />
                    </Dropdown.Toggle>
                    <Dropdown.Menu>
                      <Dropdown.Item>
                        <ul className="custom-dropdown-menu">
                          <li className="text-black">
                            <Link href="/staff/changeusername">
                              <PersonIcon />
                              <span>Change Username</span>
                            </Link>
                          </li>
                          <li>
                            <Link href="/staff/changepassword">
                              <LockIcon />
                              <span>Change Password</span>
                            </Link>
                          </li>
                          <li>
                            <Link href="/staff/changeemail">
                              <EmailIcon />
                              <span>Change Email</span>
                            </Link>
                          </li>
                          <li className="logOutButton" onClick={handleLogOut}>
                            <KeyIcon />
                            Logout
                          </li>
                        </ul>
                      </Dropdown.Item>
                    </Dropdown.Menu>
                  </Dropdown>
                </div>
              </div>
            </div>
          </nav>
          {showDrawer && (
            <div
              ref={drawerRef}
              className="fixed top-16 right-0 w-110 h-full bg-white shadow-lg z-50 transition-transform transform animate-slide-in overflow-y-auto p-4 min-w-[657px]"
            >
              <div className="flex justify-between items-center mb-2">
                <h3 className="text-lg font-semibold">Notifications</h3>
                <button
                  onClick={toggleDrawer}
                  className="text-gray-600 text-xl pointer"
                >
                  ✕
                </button>
              </div>
              <hr />
              {notifications.length > 0 && (
                <div className="flex justify-end mb-4">
                  <button
                    className="text-sm pt-2 text-gray-400 underline hover:text-blue-800 transition"
                    onClick={markAllAsRead}
                  >
                    Mark all as read
                  </button>
                </div>
              )}
              <div className="min-h-[200px] w-full">
                {loading ? (
                  <div className="flex justify-center items-center min-h-[200px]">
                    <span className="text-sm text-gray-400 animate-pulse">
                      Loading notifications...
                    </span>
                  </div>
                ) : notifications.length > 0 ? (
                  Object.keys(groupedNotifications).map((date) => (
                    <div key={date}>
                      <h5 className="text-xs text-gray-500 mb-2 mt-4">
                        {date}
                      </h5>
                      <ul className="space-y-4">
                        {groupedNotifications[date].map((notification, idx) => (
                          <li
                            key={idx}
                            className={`border-b rounded p-2 flex justify-between items-center ${
                              notification.mark_as_read === "0"
                                ? "bg-gray-100"
                                : ""
                            }`}
                          >
                            <div className="flex-1">
                              <div className="flex items-center">
                                {notification.mark_as_read === "0" && (
                                  <span className="inline-block w-2 h-2 bg-orange-500 rounded-full mr-2"></span>
                                )}
                                <h4 className="font-bold text-sm">
                                  {notification.notification_title}
                                </h4>
                              </div>
                              <p className="text-gray-600 text-sm">
                                {notification.notification_text}
                              </p>
                              <p className="text-xs text-gray-400 mt-1">
                                {new Date(
                                  notification.created_at
                                ).toLocaleTimeString()}
                              </p>
                            </div>
                            <button
                              onClick={() => markAsRead(notification.id)}
                              className="ml-3 text-blue-600 hover:text-blue-800 transition flex items-center justify-center"
                              title="Mark as Read"
                            >
                              <VisibilityIcon fontSize="small" />
                            </button>
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))
                ) : (
                  <div className="flex items-center justify-center min-h-[200px] text-sm text-gray-500">
                    No notifications
                  </div>
                )}
              </div>
            </div>
          )}
          {children}
        </div>
        {/* <style jsx>{`
          @keyframes slideIn {
            from {
              opacity: 0;
              transform: translateY(-10px);
            }
            to {
              opacity: 1;
              transform: translateY(0);
            }
          }
          .animate-slide-in {
            animation: slideIn 0.3s ease-out;
          }
        `}</style> */}
      </body>
    </html>
  );
}
